apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  labels:
    app: notes-app
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31000
  selector:
    app: notes-app
